import EStyleSheet from 'react-native-extended-stylesheet';

EStyleSheet.build({
  $contentBckg: '#F8FCFF',
  $mainColor:'#518EB6'
});

module.exports = EStyleSheet.create({
  quickLinkContainerCustom:{
    backgroundColor:'#FFFFFF',
    flex:0,
    height:70,
    alignItems:'center',
    justifyContent:'center',
    flexDirection:'row',
  },
  imgAnnuler:{
    width:25,
    height:25,
  },
  contentInfo:{
    flex:2,
    backgroundColor:'$contentBckg',
  },
  container:{
    width:'80%',
    alignSelf:'center',
  },
  head:{
    flexDirection:'row',
    paddingTop:40,
    justifyContent:'center',
    width:'90%',
    position:'relative',
    alignSelf:'center',
    alignItems:'center',
  },
  title:{
    fontSize:24,
    lineHeight:34,
    fontFamily:'droidsans',
    color:'$mainColor',
    textAlign:'center',
    letterSpacing:1,
  },
  clockContainer:{
    width:150,
    height:150,
    alignSelf:'center',
    backgroundColor:'$mainColor',
    marginTop:40,
    marginBottom:50,
    borderRadius:150,
    justifyContent:'center',
    alignItems:'center',
  },
  clockBorder:{
    width:142,
    height:142,
    justifyContent:'center',
    alignItems:'center',
    borderColor:'#FFFFFF',
    borderWidth:1,
    borderRadius:140,
  },
  timer:{
    width:'25%',
    textAlign:'center',
    color:'#FFFFFF',
    fontSize:18,
    fontFamily:'lato-light',
    lineHeight:28,
  },
  row:{
    justifyContent:'space-between',
    flexDirection:'row',
    marginBottom:20,
  },
  content:{
    alignItems:'flex-start',
    width:'45%',
  },
  label:{
    fontSize:14,
    fontFamily:'droidsans',
    letterSpacing:0.5,
    lineHeight:24,
    color:'$mainColor',
  },
  response:{
    fontSize:16,
    fontFamily:'lato-regular',
    lineHeight:26,
  },
  cancelLink:{
    position:'absolute',
    top:20,
    zIndex:111,
    left:0,
  },
  cancelLinkEpargne:{
    position:'absolute',
    top:20,
    zIndex:111,
    left:-20,
  },
  '@media (max-width: 320px)':{
    head:{
      flexDirection:'row',
      paddingTop:25,
    },
    clockContainer:{
      width:150,
      height:150,
      marginTop:20,
      marginBottom:20,
    },
    title:{
      fontSize:16,
    },
    imgAnnuler:{
      width:0,
      height:0,
    },
    cancelLinkEpargne:{
      position:'absolute',
      top:0,
      zIndex:111,
      left:0,
    },
  },
  '@media (min-width:414px) and (max-width:765px)':{
    clockContainer:{
      width:180,
      height:180,
      marginTop:40,
      marginBottom:40,
    },
    clockBorder:{
      width:172,
      height:172,
      justifyContent:'center',
      alignItems:'center',
      borderColor:'#FFFFFF',
      borderWidth:1,
      borderRadius:140,
    },
  },
  '@media (min-width:768px)':{
    head:{
      flexDirection:'row',
      paddingTop:45,
    },
    clockContainer:{
      width:300,
      height:300,
      marginTop:80,
      marginBottom:80,
    },
    clockBorder:{
      width:282,
      height:282,
    },
    timer:{
      width:'25%',
      textAlign:'center',
      color:'#FFFFFF',
      fontSize:28,
      fontFamily:'lato-light',
      lineHeight:44,
    },
    label:{
      fontSize:24,
      fontFamily:'droidsans',
      letterSpacing:0.5,
      lineHeight:34,
      color:'$mainColor',
    },
    response:{
      fontSize:24,
      paddingTop:10,
      fontFamily:'lato-regular',
      lineHeight:38,
      paddingBottom:20,
    },
    row:{
      width:'100%',
      justifyContent:'center',
      flexDirection:'row',
      marginBottom:20,
    },
    title:{
      fontSize:32,
    },
    imgAnnuler:{
      width:35,
      height:35,
    },
    cancelLink:{
      left:-20,
    },
    cancelLinkEpargne:{
      left:-40,
    },
  }
});
