import EStyleSheet from 'react-native-extended-stylesheet';

EStyleSheet.build({
  $Blue: '#235182'
});


module.exports = EStyleSheet.create({
  introContainer: {
    borderWidth:1,
    borderColor:'$Blue',
    borderRadius:5,
    marginTop:35,// 15px on arrive a la StatusBar + 20px de margin
    margin:20,
    flex:1,
  },
  container: {
    alignItems:'center',
  },
  img:{
    width:257,
    height:251,
    marginTop:25,
    marginBottom:35,
  },
  titleIntro:{
    fontSize:20,
    color:'$Blue',
    marginBottom:20,
    fontFamily:'droidsans',
  },
  link:{
    fontFamily:'lato-regular',
    fontSize:14,
    color:'#34586B',
    alignSelf:'center',
  },
  linkContainer:{
    alignSelf:'center',
    marginTop:15,
    marginBottom:15,
    borderBottomWidth:1,
  },
  introText:{
    fontSize:18,
    textAlign:'center',
    fontWeight:'100',
    lineHeight:24,
    color:'$Blue',
    paddingLeft:30,
    paddingRight:30,
    paddingBottom:30,
    fontFamily:'lato-light',
  },
  switchContainer:{
    flexDirection:'row',
    marginBottom:40,
    marginRight:21,
  },
  switcher:{
    width:19.75,
    height:15,
    borderWidth:1,
    borderColor:'$Blue',
    borderRadius:2.5,
    marginLeft:26.33,
  },
  button:{
    backgroundColor:'$Blue',
    paddingTop:15,
    paddingBottom:15,
    borderRadius:8,
    alignItems:'center',
    alignSelf:'stretch',
    marginLeft:26,
    marginRight:26,
  },
  buttonCustom:{
    backgroundColor:'$Blue',
    paddingTop:15,
    paddingBottom:15,
    borderRadius:8,
    alignItems:'center',
    alignSelf:'stretch',
    marginLeft:26,
    marginTop:45,
    marginRight:26,
  },
  buttonCustom2:{
    backgroundColor:'$Blue',
    paddingTop:15,
    paddingBottom:15,
    borderRadius:8,
    alignItems:'center',
    alignSelf:'stretch',
    marginLeft:26,
    marginTop:27,
    marginRight:26,
  },
  buttonText:{
    color:'#FFFFFF',
    fontFamily:'droidsans'
  },
  active:{
    backgroundColor:'$Blue',
    borderRadius:2.5,
    width:19.75,
    height:15,
    borderWidth:1,
    borderColor:'$Blue',
    borderRadius:2.5,
    marginLeft:26.33,
  },

  '@media (max-width: 320px)':{
    introContainer: {
      marginTop:25,// 15px on arrive a la StatusBar + 20px de margin
      margin:15,
      borderWidth:0,
    },
    img:{
      marginTop:15,
      marginBottom:20,
    },
    introText:{
      paddingBottom:20,
    },
    switchContainer:{
      marginBottom:20,
    },
    titleIntro:{
      marginBottom:10,
    },
    button:{
      width:'80%',
      alignSelf:'center',
      marginTop:0,
      marginBottom:10,
    },
    buttonCustom:{
      width:'80%',
      alignSelf:'center',
      marginTop:10,
      marginLeft:0,
      marginBottom:10,
      marginRight:0,
    },
    linkContainer:{
      alignSelf:'center',
      marginBottom:15,
      borderBottomWidth:1,
    },
    buttonCustom2:{
      width:'80%',
      alignSelf:'center',
      marginLeft:0,
      marginTop:5,
      marginBottom:10,
      marginRight:0,
    },
  },
  '@media (min-width:414px) and (max-width:765px)':{
    introText:{
      paddingBottom:50,
    },
    switchContainer:{
      marginBottom:50,
    },
    button:{
      marginTop:40,
      marginBottom:10,
    },
    buttonCustom2:{
      marginTop:50,
      marginBottom:10,
    },
  },
  '@media (min-width:768px)':{
    img:{
      width:357,
      height:350,
    },
    titleIntro:{
      fontSize:32,
      marginBottom:40,
    },
    introText:{
      fontSize:28,
      textAlign:'center',
      fontWeight:'100',
      lineHeight:38,
      color:'$Blue',
      paddingLeft:30,
      paddingRight:30,
      paddingBottom:80,
    },
    switchContainer:{
      flexDirection:'row',
      marginBottom:160,
      marginRight:21,
    },
    switcher:{
      width:29.75,
      height:25,
    },
    active:{
      width:29.75,
      height:25,
    },
    button:{
      paddingTop:20,
      paddingBottom:20,
    },
    buttonCustom:{
      paddingTop:20,
      paddingBottom:20,
    },
    buttonCustom2:{
      paddingTop:20,
      paddingBottom:20,
    },
    buttonText:{
      color:'#FFFFFF',
      fontFamily:'droidsans',
      fontSize:24,
    },
    link:{
      fontFamily:'lato-regular',
      fontSize:18,
      color:'#34586B',
      alignSelf:'center',
    },
    linkContainer:{
      alignSelf:'center',
      marginTop:20,
      marginBottom:15,
      borderBottomWidth:1,
    },
  }
});
