import EStyleSheet from 'react-native-extended-stylesheet';

EStyleSheet.build({
  $mainBckg: '#F8FCFF',
  $nameColor:'#6FA4C7',
  $montantBckg:'#7AB3E3',
  $mainColor:'#538EB6',
  $text:'#333333'
});

module.exports = EStyleSheet.create({
  iconTitle:{
    width:40,
    height:36,
  },
  content:{
    width:'85%',
    alignSelf:'center',
    marginTop:30,
    marginBottom:30,
    flex:0.7,
  },
  contentHead:{
    flexDirection:'row',
    alignItems:'center',
  },
  title:{
    fontSize:14,
    fontFamily:'droidsans',
    color:'$nameColor',
    marginLeft:15,
  },
  text:{
    fontSize:15,
    fontFamily:'lato-light',
    lineHeight:23,
    color:'$text',
    paddingTop:15,
  },
  formContainer:{
    backgroundColor:'$mainBckg',
    flex:1,
  },
  titleForm:{
    fontSize:18,
    fontFamily:'droidsans',
    color:'#8AB1DC',
    textAlign:'center',
    marginTop:60,
  },
  formContent:{
    flexDirection:'row',
    width:'85%',
    alignSelf:'center',
    marginTop:30,
  },
  iconContainer:{
    backgroundColor:'$mainColor',
    width:60,
    height:60,
    alignItems:'center',
    justifyContent:'center',
    marginRight:2,
  },
  iconForm:{
    width:40,
    height:40,
  },
  input:{
    backgroundColor:'#FFFFFF',
    width:'67%',
    borderTopWidth:1,
    borderRightWidth:1,
    borderBottomWidth:1,
    borderColor:'#EFEFEF',
    alignItems:'center',
    justifyContent:'center',
    position:'relative'
  },
  inputText:{
    fontSize:30,
    fontFamily:'lato-light',
    marginLeft:20,
    height:30,
  },
  euro:{
    fontSize:30,
    fontFamily:'lato-light',
    backgroundColor:'transparent',
    position:'absolute',
    right:30,
  },
  actionContainer:{
    flexDirection:'row',
  },
  cancelContainer:{
    backgroundColor:'#E3F4FF',
    width:'50%',
    alignItems:'center',
    justifyContent:'center',
    paddingTop:20,
    paddingBottom:20,
  },
  checkContainer:{
    backgroundColor:'#D2EDFF',
    width:'50%',
    alignItems:'center',
    justifyContent:'center',
    paddingTop:20,
    paddingBottom:20,
  },
  cancelIcon:{
    width:30,
    height:30,
  },
  checkIcon:{
    width:30,
    height:21,
  }
});
