import EStyleSheet from 'react-native-extended-stylesheet';

EStyleSheet.build({
  $headerColor: '#518BB2',
});

module.exports = EStyleSheet.create({
  header:{
    backgroundColor:'$headerColor',
  },
  navBar:{
    marginTop:35,
    flexDirection:'row',
    justifyContent:'space-between',
    paddingBottom:10,
    alignItems:'center',
  },
  backLink:{
    flexDirection:'row',
  },
  backIcone:{
    width:8.66,
    height:15,
    marginLeft:10,
  },
  backText:{
    fontSize:15,
    marginLeft:7,
    color:'#FFFFFF',
    position:'relative',
    bottom:2,
  },
  navTitle:{
    color:'#FFFFFF',
    fontWeight:'500',
    fontSize:15,
    marginRight:20,
    position:'relative',
    bottom:2,
  },
  navTitleCustom:{
    color:'#FFFFFF',
    fontWeight:'500',
    fontSize:15,
    marginRight:105,
    textAlign:'center',
    position:'relative',
    bottom:2,
  },
  navTitleCustomLimit:{
    color:'#FFFFFF',
    fontWeight:'500',
    fontSize:15,
    marginRight:130,
    textAlign:'center',
    position:'relative',
    bottom:2,
  },
  navTitleCustomPret:{
    color:'#FFFFFF',
    fontWeight:'500',
    fontSize:15,
    marginRight:125,
    textAlign:'center',
    position:'relative',
    bottom:2,
  },
  add:{
    marginRight:31,
  },
  addIcone:{
    width:25,
    height:25,
  },
  '@media (max-width: 320px)':{
    navTitleCustomLimit:{
      marginRight:100,
    },
    navTitleCustom:{
      marginRight:70,
    },
    navTitleCustomPret:{
      marginRight:100,
    },
  },
  '@media (min-width:380px) and (max-width:768px)':{
    navBar:{
      marginTop:45,
      paddingBottom:15,
    },
    backIcone:{
      width:12.66,
      height:19,
      marginLeft:40,
    },
    backText:{
      fontSize:18,
      marginLeft:15,
      color:'#FFFFFF',
      position:'relative',
      bottom:2,
    },
    navTitle:{
      fontSize:18,
      marginRight:50,
    },
    navTitleCustom:{
      fontSize:18,
      marginRight:290,
    },
    navTitleCustomLimit:{
      fontSize:18,
      marginRight:320,
      bottom:2,
    },
    navTitleCustomPret:{
      fontSize:18,
      marginRight:320,
    },
    add:{
      marginRight:31,
    },
    addIcone:{
      width:30,
      height:30,
    },
  }
});
